### ISSUE TITLE
"Go to Work" fails after sim changes

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#14]
(I'm aware this is a known issue)
At a specific time in the day, the sim changes for the robot factory job and walks up to the carpool. Aaaaand... nothing!
I'm aware that in the global server the sim would probably be transported to the job lot, but right now it would be a good idea to either simulate the sim "going to work" and receiving a paycheck before changing back to normal clothes, or maybe just having the "Go to Work" interaction disabled for the time being.
I'd like to hear your comments on this!

**Comment by RHY3756547** [comment]
Requires a global server to allocate job lots to people on demand, and connect them together from many different lots. 

Obviously impossible to implement without the real server backing it.

**Comment by jackmawer** [comment]
Understandable, but I still think just disabling it until the global server is ready would be a good temporary measure to improve QoL.

**Comment by RHY3756547** [comment]
The goal of FreeSO is to recreate TSO gameplay, not lock parts of it off. The carpool comes right now because I'm forcing everyone to have a job, which is the intended behaviour. We'd have to make an iff patch to change this functionality, and ideally the less we make the better.

**Comment by jackmawer** [comment]
Alright, understood. It's not that much of a convenience anyway.
Since this is a wontfix, I'll close this issue.
