### ISSUE TITLE
When interacting with self or other sims, queue reads "Idle"

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#16]
This is a weird one, also reported in Discord.
It's kinda hard to explain, but is pretty game breaking. See the following GIF:

![Everything returns "Idle"!](http://i.imgur.com/0FpCkjy.gif)

Hopefully this is fixed next build ;)

**Comment by RHY3756547** [comment]
Do not make issues for immediately obvious regressions. Issues are for longer term problems which merit discussion and won't be fixed immediately.

Will be fixed in next master dist. I've been fixing up server-rebuild the next """build""" will be completely unusable.
