### ISSUE TITLE
[Low-priority] Server sim's needs decay

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#17]
The "server" sim from Charvatia has his/her needs decay, which means a tombstone is placed multiple times. Despite you needing to click through a dialog to die more than 2 times, Rhys has added a timeout to this, meaning the server sim can now spam gravestones.

A potential solution to this would be freezing the server sim's needs meaning that they wouldn't have needs decaying causing death and cause this spam. 

Another solution could be simply disabling death for the sim. This would stop the gravestone spam, but the invisible server sim would still complain about low needs! 

Finally, we could simply *remove* the gravestones entirely, or the trigger to place them on death, thereby resolving the potential for trolls to die in front of entrances or certain areas with the intention of blocking out other players - with permissions, this means the players have to wait until a build/buy roomie or an admin to join and remove the tombstone.
However, removing tombstones means this potential trolling method is impossible, which would improve the experience for everyone!

**Comment by RHY3756547** [comment]
The charvatia server sim is a temporary measure. In future server will communicate to owned lots via general message commands, if even necessary.

**Comment by jackmawer** [comment]
Alright, that's fine ;)
