### ISSUE TITLE
[VM] Animation does not reset after a VMRoutingFrame.

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#18]
When using the Electronic Information Terminal, occasionally the sim gets stuck in a strange walking in place animation.

![Look at my Moonwalk!](http://i.imgur.com/0pXEFNP.gif)

Should probably look into that.

**Comment by RHY3756547** [comment]
Animation currently does not reset after a routing frame. This interaction plays no animation, so it should just return to the default breathing animation. (see VMAnimateSim for the animation reset functionality)

**Comment by RHY3756547** [comment]
See #65
