### ISSUE TITLE
IPA Installation

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#31]
Excuse the issue creation, but I decided it would be best to pester you here if at all.

It's now possible to install unsigned IPA files on a non-jailbroken device using "Cydia Impactor". It's available [here](http://www.cydiaimpactor.com/).

That is all.

**Comment by jackmawer** [comment]
I can't read. Excuse my absolute stupidity.

**Comment by RHY3756547** [comment]
Fucking hell, really??
