### ISSUE TITLE
Empty wiki

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#9]
It would probably be a good idea to have at least some *basic* information on the wiki so people can test the modifications they make.

**Comment by Blayer98** [comment]
That's not related to this GitHub project. Tell Rhys in Discord rather than here.

**Comment by RHY3756547** [comment]
This is not a code issue.

**Comment by jackmawer** [comment]
This is related to the GitHub project, because it's _part of the GitHub project_...

**Comment by RHY3756547** [comment]
Please don't become zack #2.
